name = "barber-server"
main = "src/index.js"
compatibility_date = "2024-02-07"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "barber-db"
database_id = "833f15c1-bda9-43fa-a890-0dbaf04514e8"

[vars]
GLOBAL_APP_NAME = "Universal Scheduler"
GLOBAL_BRAND_COLOR = "#0066ffff"
WA_BRIDGE_KEY = "universal-secret-key"
WA_BRIDGE_URL = "https://nisi-marbly-maeve.ngrok-free.dev"


[ai]
binding = "AI"

[triggers]
crons = ["30 10 * * *"]
